const API_BASE = '/api';
const API_VERSION = '/v1';
const API_ENDPOINT = `${API_BASE}${API_VERSION}`;

export const API_ENDPOINTS = {
  API_BASE,
  API_VERSION,
  API_ENDPOINT,

  AUTH: {
    BASE: `${API_ENDPOINT}/auth`,
    LOGIN: `${API_ENDPOINT}/auth/login`,
  },
  ACCOUNT: {
    BASE: `${API_ENDPOINT}/account`,
    GET: `${API_ENDPOINT}/account`,
    GET_CURRENT: `${API_ENDPOINT}/account/current`,
    GET_MANY: `${API_ENDPOINT}/account/many`,
    GET_BY_ID: (id: string | number) => `${API_ENDPOINT}/account/${id}`,
    CREATE: `${API_ENDPOINT}/account`,
    CREATE_WITH_CITIZEN_CARD: `${API_ENDPOINT}/account/create-with-citizen-card`,
    UPDATE: (id: string | number) => `${API_ENDPOINT}/account/${id}`,
    DELETE: (id: string | number) => `${API_ENDPOINT}/account/${id}`,
  },
  PRODUCTS: {
    BASE: `${API_ENDPOINT}/product`,
    GET_ALL: `${API_ENDPOINT}/product`,
    GET_BY_ID: (id: string) => `${API_ENDPOINT}/product/${id}`,
    GET_WITH_FRAME_INFO: (id: string) => `${API_ENDPOINT}/product/${id}/with-frame-info`,
    GET_ACCESSORIES_BY_PARENT_ID: (id: string) => `${API_ENDPOINT}/product/${id}/accessories`,
    GET_BY_SLUG: (slug: string) => `${API_ENDPOINT}/product/slug/${slug}`,
    GET_BY_SHOP_ID: (shopId: string) => `${API_ENDPOINT}/product/shop/${shopId}`,
    GET_REVIEWS: (productId: string) => `${API_ENDPOINT}/product/${productId}/reviews`,
    GET_SHOP_FRAME: (shopId: string) => `${API_ENDPOINT}/product/frame-group/shop/${shopId}`,
    GET_PRODUCT_IMAGES: (productId: string) => `${API_ENDPOINT}/product/product-images/${productId}`,
    GET_SHOP_ACCESSORY: (shopId: string) => `${API_ENDPOINT}/product/accessory/shop/${shopId}`,
    GET_MODEL_3D: `${API_ENDPOINT}/product/frame-group/model-3d`,
    GET_COLORS: `${API_ENDPOINT}/product/frame-variant/colors`,
    GET_VIRTUAL_TRY_ON_PARAMS: (frameGroupId: string) => `${API_ENDPOINT}/product/frame-group/virtual-try-on-params/${frameGroupId}`,

    CREATE_FRAME_GROUP: `${API_ENDPOINT}/product/frame-group`,
    CREATE_FRAME_VARIANT: `${API_ENDPOINT}/product/frame-variant`,
    CREATE_ACCESSORY: `${API_ENDPOINT}/product/accessory`,
    CREATE_ACCESSORY_VARIANT: `${API_ENDPOINT}/product/accessory/variant`,

    ACTIVATE_PRODUCT: (id: string) => `${API_ENDPOINT}/product/${id}/activate`,
    SET_FEATURE_PRODUCT: (id: string) => `${API_ENDPOINT}/product/feature/${id}`,
    UPDATE_FRAME_GROUP: (id: string) => `${API_ENDPOINT}/product/frame-group/${id}`,
    DELETE_FRAME_GROUP: (id: string) => `${API_ENDPOINT}/product/frame-group/${id}`,
    UPDATE_FRAME_VARIANT: (id: string) => `${API_ENDPOINT}/product/frame-variant/${id}`,
    DELETE_FRAME_VARIANT: (id: string) => `${API_ENDPOINT}/product/frame-variant/${id}`,
    UPDATE_ACCESSORY: (id: string) => `${API_ENDPOINT}/product/accessory/${id}`,
    DELETE_ACCESSORY: (id: string) => `${API_ENDPOINT}/product/accessory/${id}`,
    UPDATE_ACCESSORY_VARIANT: (id: string) => `${API_ENDPOINT}/product/accessory/variant/${id}`,
    DELETE_ACCESSORY_VARIANT: (id: string) => `${API_ENDPOINT}/product/accessory/variant/${id}`,
    UPLOAD_3D_MODEL: `${API_ENDPOINT}/product/frame-variant/upload-3d-model`,
  },
  CATEGORIES: {
    BASE: `${API_ENDPOINT}/categories`,
    GET_ALL: `${API_ENDPOINT}/categories`,
  },
  LENS: {
    BASE: `${API_ENDPOINT}/lens-catalog`,
    CATALOG_FOR_FRAME: (frameVariantId: string) => `${API_ENDPOINT}/lens-catalog/for-frame/${frameVariantId}`,
    GET_ALL: `${API_ENDPOINT}/lenses`,
    CREATE: `${API_ENDPOINT}/lenses`,
    GET_BY_ID: (id: string) => `${API_ENDPOINT}/lenses/${id}`,
    UPDATE: (id: string) => `${API_ENDPOINT}/lenses/${id}`,
    CREATE_FOR_FRAME: (frameVariantId: string) => `${API_ENDPOINT}/lenses/for-frame/${frameVariantId}`,
    CREATE_FOR_FRAME_GROUP: (frameGroupId: string) => `${API_ENDPOINT}/lenses/for-frame-group/${frameGroupId}`,
    CREATE_FEATURE: `${API_ENDPOINT}/lenses/features`,
    UPDATE_FEATURE: (featureId: string) => `${API_ENDPOINT}/lenses/features/${featureId}`,
    FEATURE_FRAME_COMPATIBILITIES: `${API_ENDPOINT}/lenses/feature-frame-compatibilities`,
    FEATURE_FRAME_COMPATIBILITY_BY_ID: (compatibilityId: string) => `${API_ENDPOINT}/lenses/feature-frame-compatibilities/${compatibilityId}`,
    CREATE_TINT: `${API_ENDPOINT}/lenses/tints`,
    UPDATE_TINT: (tintId: string) => `${API_ENDPOINT}/lenses/tints/${tintId}`,
    CREATE_USAGE: `${API_ENDPOINT}/lenses/usages`,
    UPDATE_USAGE: (usageId: string) => `${API_ENDPOINT}/lenses/usages/${usageId}`,
    CREATE_FEATURE_MAPPING: (lensId: string) => `${API_ENDPOINT}/lenses/${lensId}/feature-mappings`,
    UPDATE_FEATURE_MAPPING: (lensId: string, mappingId: string) => `${API_ENDPOINT}/lenses/${lensId}/feature-mappings/${mappingId}`,
    CREATE_TINT_OPTION: (lensId: string) => `${API_ENDPOINT}/lenses/${lensId}/tint-options`,
    UPDATE_TINT_OPTION: (lensId: string, optionId: string) => `${API_ENDPOINT}/lenses/${lensId}/tint-options/${optionId}`,
    CREATE_USAGE_RULE: (lensId: string) => `${API_ENDPOINT}/lenses/${lensId}/usage-rules`,
    UPDATE_USAGE_RULE: (lensId: string, ruleId: string) => `${API_ENDPOINT}/lenses/${lensId}/usage-rules/${ruleId}`,
    CREATE_PROGRESSIVE_OPTION: (lensId: string) => `${API_ENDPOINT}/lenses/${lensId}/progressive-options`,
    UPDATE_PROGRESSIVE_OPTION: (lensId: string, optionId: string) => `${API_ENDPOINT}/lenses/${lensId}/progressive-options/${optionId}`,
  },
  PRESCRIPTIONS: {
    BASE: `${API_ENDPOINT}/prescriptions`,
    GET_MY_PRESCRIPTIONS: `${API_ENDPOINT}/prescriptions/me`,
    GET_BY_ID: (id: string) => `${API_ENDPOINT}/prescriptions/${id}`,
    CREATE: `${API_ENDPOINT}/prescriptions`,
    UPDATE: (id: string) => `${API_ENDPOINT}/prescriptions/${id}`,
    DELETE: (id: string) => `${API_ENDPOINT}/prescriptions/${id}`,
  },
  VALIDATION: {
    BASE: `${API_ENDPOINT}/validation`,
    LENS_FRAME: `${API_ENDPOINT}/validation/lens-frame`,
    PRESCRIPTION: `${API_ENDPOINT}/prescriptions/validate`,
  },
  PLATFORM_SETTINGS: {
    BASE: `${API_ENDPOINT}/platform-settings`,
    PRESCRIPTION_VALUES: {
      ALL: `${API_ENDPOINT}/platform-settings/prescription-values`,
      SPHERE: `${API_ENDPOINT}/platform-settings/prescription-values/sphere`,
      CYLINDER: `${API_ENDPOINT}/platform-settings/prescription-values/cylinder`,
      ADD: `${API_ENDPOINT}/platform-settings/prescription-values/add`,
      PD: `${API_ENDPOINT}/platform-settings/prescription-values/pd`,
      PD_MONOCULAR: `${API_ENDPOINT}/platform-settings/prescription-values/pd-monocular`,
    },
    CURRENT: `${API_ENDPOINT}/platform-settings/current`,
    HISTORY: `${API_ENDPOINT}/platform-settings/history`,
    UPDATE_AS_NEW: `${API_ENDPOINT}/platform-settings/admin/update-as-new`,
    RESET_PRESCRIPTION: `${API_ENDPOINT}/platform-settings/reset-prescription-config`,
    RESET_REFUND: `${API_ENDPOINT}/platform-settings/reset-refund-policy-config`,
  },
  CART: {
    BASE: `${API_ENDPOINT}/cart`,
    CREATE: `${API_ENDPOINT}/cart`,
    GET_ACTIVE: `${API_ENDPOINT}/cart/active`,
    GET_MY_CART: `${API_ENDPOINT}/cart/me`,
    ADD_ITEM: (cartId: string) => `${API_ENDPOINT}/cart/${cartId}/items`,
    UPDATE_ITEM: (cartId: string, itemId: string) => `${API_ENDPOINT}/cart/${cartId}/items/${itemId}`,
    REMOVE_ITEM: (cartId: string, itemId: string) => `${API_ENDPOINT}/cart/${cartId}/items/${itemId}`,
    DELETE: (cartId: string) => `${API_ENDPOINT}/cart/${cartId}`,
  },
  ORDERS: {
    BASE: `${API_ENDPOINT}/orders`,
    CREATE: `${API_ENDPOINT}/orders`,
    GET_MY_ORDERS: `${API_ENDPOINT}/orders`,
    GET_BY_ID: (orderId: string) => `${API_ENDPOINT}/orders/${orderId}`,
    CANCEL: (orderId: string) => `${API_ENDPOINT}/orders/${orderId}/cancel`,
    CANCEL_SHOP_ORDER: (orderId: string, shopOrderId: string) => `${API_ENDPOINT}/orders/${orderId}/shop-orders/${shopOrderId}/cancel`,
    CANCEL_ORDER_ITEM: (orderId: string, itemId: string) => `${API_ENDPOINT}/orders/${orderId}/items/${itemId}/cancel`,
    RE_ORDER: (orderId: string) => `${API_ENDPOINT}/orders/${orderId}/re-order`,
    CONFIRM_RECEIVED: (orderId: string) => `${API_ENDPOINT}/orders/${orderId}/confirm-received`,
    DELIVERY_FAILED: (orderId: string) => `${API_ENDPOINT}/orders/${orderId}/delivery-failed`,
    REFUSE_DELIVERY: (orderId: string) => `${API_ENDPOINT}/orders/${orderId}/refuse-delivery`,
    FORCE_STATUS: (orderId: string) => `${API_ENDPOINT}/orders/${orderId}/admin/force-status`,
  },
  PAYMENTS: {
    CREATE_VNPAY: `${API_ENDPOINT}/payments/create-vnpay`,
    VNPAY_RETURN: `${API_ENDPOINT}/payments/vnpay-return`,
    STATUS: (orderId: string) => `${API_ENDPOINT}/payments/status/${orderId}`,
    TOP_UP: `${API_ENDPOINT}/payments/top-up`,
    PAY_FROM_WALLET: `${API_ENDPOINT}/payments/pay-from-wallet`,
  },
  USER_WALLET: {
    BASE: `${API_ENDPOINT}/wallet`,
    TRANSACTIONS: `${API_ENDPOINT}/wallet/transactions`,
    WITHDRAWALS: `${API_ENDPOINT}/wallet/withdrawals`,
    CANCEL_WITHDRAWAL: (id: string) => `${API_ENDPOINT}/wallet/withdrawals/${id}/cancel`,
  },
  USER_BANK_ACCOUNTS: {
    BASE: `${API_ENDPOINT}/user/bank-accounts`,
    SET_DEFAULT: (id: string) => `${API_ENDPOINT}/user/bank-accounts/${id}/default`,
    DELETE: (id: string) => `${API_ENDPOINT}/user/bank-accounts/${id}`,
  },
  USER_ADDRESSES: {
    BASE: `${API_ENDPOINT}/user-addresses`,
    GET_BY_ID: (id: string) => `${API_ENDPOINT}/user-addresses/${id}`,
    UPDATE: (id: string) => `${API_ENDPOINT}/user-addresses/${id}`,
    DELETE: (id: string) => `${API_ENDPOINT}/user-addresses/${id}`,
    SET_DEFAULT: (id: string) => `${API_ENDPOINT}/user-addresses/${id}/set-default`,
  },
  WARRANTY: {
    CLAIMS: `${API_ENDPOINT}/warranty-claims`,
    CLAIM_BY_ID: (id: string) => `${API_ENDPOINT}/warranty-claims/${id}`,
    PAY_VNPAY: (id: string) => `${API_ENDPOINT}/warranty-claims/${id}/pay/vnpay`,
    PAY_WALLET: (id: string) => `${API_ENDPOINT}/warranty-claims/${id}/pay/wallet`,
    REJECT_QUOTE: (id: string) => `${API_ENDPOINT}/warranty-claims/${id}/reject-quote`,
    RECEIVE: (id: string) => `${API_ENDPOINT}/warranty-claims/${id}/receive`,
    GHN_STATUS: (id: string) => `${API_ENDPOINT}/warranty-claims/${id}/ghn-status`,
  },
  SHOP_WARRANTY: {
    CLAIMS: `${API_ENDPOINT}/shop/warranty-claims`,
    CLAIM_BY_ID: (id: string) => `${API_ENDPOINT}/shop/warranty-claims/${id}`,
    APPROVE: (id: string) => `${API_ENDPOINT}/shop/warranty-claims/${id}/approve`,
    RECEIVE: (id: string) => `${API_ENDPOINT}/shop/warranty-claims/${id}/receive`,
    QUOTE: (id: string) => `${API_ENDPOINT}/shop/warranty-claims/${id}/quote`,
    REJECT: (id: string) => `${API_ENDPOINT}/shop/warranty-claims/${id}/reject`,
    COMPLETE: (id: string) => `${API_ENDPOINT}/shop/warranty-claims/${id}/complete`,
    SERVICE_PRICES: `${API_ENDPOINT}/shop/warranty-service-prices`,
    SERVICE_PRICE_BY_ID: (id: string) => `${API_ENDPOINT}/shop/warranty-service-prices/${id}`,
    POLICIES: `${API_ENDPOINT}/shop/warranty-policies`,
    POLICY_BY_ID: (id: string) => `${API_ENDPOINT}/shop/warranty-policies/${id}`,
    ISSUE_TYPES: `${API_ENDPOINT}/shop/warranty-issue-types`,
    ISSUE_TYPE_BY_ID: (id: string) => `${API_ENDPOINT}/shop/warranty-issue-types/${id}`,
  },
  WARRANTY_PUBLIC: {
    SERVICE_PRICES_BY_SHOP: (shopId: string) => `${API_ENDPOINT}/shops/${shopId}/warranty-service-prices`,
    POLICIES_BY_SHOP: (shopId: string) => `${API_ENDPOINT}/shops/${shopId}/warranty-policies`,
    ISSUE_TYPES_BY_SHOP: (shopId: string) => `${API_ENDPOINT}/shops/${shopId}/warranty-issue-types`,
  },
  RETURNS: {
    REQUESTS: `${API_ENDPOINT}/return-requests`,
    REQUEST_BY_ID: (id: string) => `${API_ENDPOINT}/return-requests/${id}`,
    CANCEL: (id: string) => `${API_ENDPOINT}/return-requests/${id}/cancel`,
  },
  SHOP_INVENTORY: {
    GET: (shopId: string) => `${API_ENDPOINT}/shop/inventory/${shopId}`,
    SET_STOCK: (shopId: string, variantId: string) => `${API_ENDPOINT}/shop/inventory/${shopId}/variant/${variantId}`,
  },
  SHOP_WALLET: {
    BASE: `${API_ENDPOINT}/shop/wallet`,
    WITHDRAWALS: `${API_ENDPOINT}/shop/wallet/withdrawals`,
    CANCEL_WITHDRAWAL: (id: string) => `${API_ENDPOINT}/shop/wallet/withdrawals/${id}/cancel`,
    TRANSACTIONS: `${API_ENDPOINT}/shop/wallet/transactions`,
  },
  SHOP_BANK_ACCOUNTS: {
    BASE: `${API_ENDPOINT}/shops/bank-accounts`,
    BY_ID: (id: string) => `${API_ENDPOINT}/shops/bank-accounts/${id}`,
    SET_DEFAULT: (id: string) => `${API_ENDPOINT}/shops/bank-accounts/${id}/default`,
  },
  SHOPS: {
    LIST: `${API_ENDPOINT}/shops`,
    GET_BY_ID: (id: string) => `${API_ENDPOINT}/shops/${id}`,
    MY_SHOPS: `${API_ENDPOINT}/shops/my-shops`,
    MY_SHOP_BY_ID: (id: string) => `${API_ENDPOINT}/shops/my-shops/${id}`,
    MY_SHOP_RESUBMIT: (id: string) => `${API_ENDPOINT}/shops/my-shops/${id}/resubmit`,
    MY_SHOP_REGISTRATION: (id: string) => `${API_ENDPOINT}/shops/my-shops/${id}/registration`,
    MY_SHOP_UPLOAD_LOGO: (id: string) => `${API_ENDPOINT}/shops/my-shops/${id}/upload-logo`,
    MY_SHOP_DEACTIVATION_STATUS: (id: string) => `${API_ENDPOINT}/shops/my-shops/${id}/deactivation-status`,
    MY_SHOP_CLOSURE_STATUS: (id: string) => `${API_ENDPOINT}/shops/my-shops/${id}/closure-status`,
  },
  ADMIN: {
    STATS: {
      OVERVIEW: `${API_ENDPOINT}/admin/stats/overview`,
      SHOPS: `${API_ENDPOINT}/admin/stats/shops`,
    },
    SHOPS: {
      REQUESTS: `${API_ENDPOINT}/admin/shops/requests`,
      REVIEW: `${API_ENDPOINT}/admin/shops/review`,
      DEACTIVATE: (shopId: string) => `${API_ENDPOINT}/admin/shops/${shopId}/deactivate`,
      REACTIVATE: (shopId: string) => `${API_ENDPOINT}/admin/shops/${shopId}/reactivate`,
      CLOSE: (shopId: string) => `${API_ENDPOINT}/admin/shops/${shopId}/close`,
      CANCEL_CLOSE: (shopId: string) => `${API_ENDPOINT}/admin/shops/${shopId}/close/cancel`,
      CANCEL_DEACTIVATE: (shopId: string) => `${API_ENDPOINT}/admin/shops/${shopId}/deactivate/cancel`,
      DEACTIVATION_STATUS: (shopId: string) => `${API_ENDPOINT}/shops/my-shops/${shopId}/deactivation-status`,
      CLOSURE_STATUS: (shopId: string) => `${API_ENDPOINT}/shops/my-shops/${shopId}/closure-status`,
    },
    USERS: {
      LIST: `${API_ENDPOINT}/admin/users`,
      GET_BY_ID: (id: string) => `${API_ENDPOINT}/admin/users/${id}`,
      SET_ROLES: (id: string) => `${API_ENDPOINT}/admin/users/${id}/roles`,
      SET_STATUS: (id: string) => `${API_ENDPOINT}/admin/users/${id}/status`,
      ORDERS: (id: string) => `${API_ENDPOINT}/admin/users/${id}/orders`,
      REFUNDS: (id: string) => `${API_ENDPOINT}/admin/users/${id}/refunds`,
      WARRANTIES: (id: string) => `${API_ENDPOINT}/admin/users/${id}/warranties`,
    },
    ORDERS: {
      LIST: `${API_ENDPOINT}/admin/orders`,
      GET_BY_ID: (orderId: string) => `${API_ENDPOINT}/admin/orders/${orderId}`,
      CANCEL: (orderId: string) => `${API_ENDPOINT}/admin/orders/${orderId}/cancel`,
    },
    REFUNDS: {
      LIST: `${API_ENDPOINT}/admin/refunds`,
      GET_BY_ID: (refundId: string) => `${API_ENDPOINT}/admin/refunds/${refundId}`,
      REVIEW: (refundId: string) => `${API_ENDPOINT}/admin/refunds/${refundId}/review`,
      REVIEW_APPEAL: (refundId: string) => `${API_ENDPOINT}/admin/refunds/${refundId}/appeal/review`,
      REVIEW_REQUEST: (refundId: string) => `${API_ENDPOINT}/refunds/${refundId}/review`,
      UPDATE: (refundId: string) => `${API_ENDPOINT}/refunds/${refundId}`,
    },
    WARRANTIES: {
      LIST: `${API_ENDPOINT}/admin/warranties`,
      GET_BY_ID: (claimId: string) => `${API_ENDPOINT}/admin/warranties/${claimId}`,
    },
    WALLET: {
      SUMMARY: `${API_ENDPOINT}/admin/wallet/summary`,
      USER_TRANSACTIONS: `${API_ENDPOINT}/admin/wallet/user-transactions`,
      SHOP_TRANSACTIONS: `${API_ENDPOINT}/admin/wallet/shop-transactions`,
      PAYMENT_TRANSACTIONS: `${API_ENDPOINT}/admin/wallet/payment-transactions`,
      USER_WITHDRAWALS: `${API_ENDPOINT}/admin/wallet/user-withdrawals`,
      SHOP_WITHDRAWALS: `${API_ENDPOINT}/admin/wallet/shop-withdrawals`,
      APPROVE_USER_WITHDRAWAL: (id: string) => `${API_ENDPOINT}/admin/wallet/user-withdrawals/${id}/approve`,
      REJECT_USER_WITHDRAWAL: (id: string) => `${API_ENDPOINT}/admin/wallet/user-withdrawals/${id}/reject`,
      APPROVE_SHOP_WITHDRAWAL: (id: string) => `${API_ENDPOINT}/admin/wallet/shop-withdrawals/${id}/approve`,
      REJECT_SHOP_WITHDRAWAL: (id: string) => `${API_ENDPOINT}/admin/wallet/shop-withdrawals/${id}/reject`,
    },
  },
  USER_RECOMMENDATION: {
    GET_MY: `${API_BASE}/users/recommendation`,
    CREATE: `${API_BASE}/users/recommendation`,
    UPDATE_NAME: (id: string) => `${API_BASE}/users/recommendation/${id}`,
    DELETE: (id: string) => `${API_BASE}/users/recommendation/${id}`,
  },
} as const;


export const PAGE_ENDPOINTS = {
  HOME: '/home',
  PERMISSION_DENIED_ENDPOINT: '/denied',
  DASHBOARD: '/admin/dashboard',

  AUTH: {
    LOGIN: `/login`,
    REGISTER: `/register`,
  },

  TRACKING: {
    DELIVERY: `/tracking/delivery`,
    SHIPMENT_DETAIL: `/tracking/delivery/:id`,
    SHOPS: `/tracking/shops`,
    SHOP_DETAIL: `/tracking/shops/:id`,
  },

  SHOP: {
    REGISTER: `/shop/register`,
    RESUBMIT: `/shop/resubmit`,
    PROFILE: `/shop/profile`,
    PRODUCT_FRAME: `/shop/product/frame`,
    CREATE_FRAME: `/shop/product/frame/create`,
    CREATE_LENS: `/shop/product/lens/create`,
    DASHBOARD: `/shop/dashboard`,
    EDIT_PROFILE: `/shop/edit-profile`,
    BANK_ACCOUNTS: `/shop/bank-accounts`,
    WALLET: `/shop/wallet`,
    PRODUCTS: `/shop/products`,
    PRODUCT_LENS: `/shop/products/lenses`,
    LENS_DETAIL: (lensId: string) => `/shop/products/lenses/detail/${lensId}`,
    EDIT_LENS: (lensId: string) => `/shop/products/lenses/${lensId}/edit`,

    // Product Accessory
    PRODUCT_ACCESSORY: `/shop/product/accessory`,
    CREATE_ACCESSORY: `/shop/product/accessory/create`,

    PRODUCT_VERIFICATION: `/shop/product-verfication`,

    ORDERS: `/shop/orders`,
    ORDER_DETAIL: `/shop/orders/:id`,
    REFUND_REVIEW: `/shop/refunds/review`,
    STAFF: `/shop/staff`,
    WARRANTY: `/shop/warranty`,
    WARRANTY_POLICIES: `/shop/warranty/policies`,
    WARRANTY_ISSUE_TYPES: `/shop/warranty/issue-types`,
  },

  ADMIN: {
    SHOP_APPROVAL: `/admin/shop-approval`,
    USER_MANAGEMENT: `/admin/users`,
    USER_DETAIL: `/admin/users/:id`,
    ORDERS: `/admin/orders`,
    ORDER_DETAIL: `/admin/orders/:id`,
    REFUNDS: `/admin/refunds`,
    REFUND_DETAIL: `/admin/refunds/:id`,
    WARRANTIES: `/admin/warranties`,
    WARRANTY_DETAIL: `/admin/warranties/:id`,
    TRANSACTIONS: `/admin/transactions`,
    VERIFY_PRODUCT: `/admin/verify-product`,
    SETTINGS: `/admin/settings`,
  },

  ORDER: {
    MY_ORDERS: `/my-orders`,
  },

  WARRANTY: {
    MAIN: `/warranty`,
  },

  REFUND: {
    BUYER_LIST: `/user/refunds`,
    BUYER_DETAIL: `/user/refunds/:requestId`,
    BUYER_CREATE: `/user/refunds/create`,
    SELLER_LIST: `/shop/refunds`,
    SELLER_DETAIL: `/shop/refunds/:requestId`,
  },

  USER: {
    PROFILE: `/users/me`,
    WALLET: `/wallet`,
    BANK_ACCOUNTS: `/user/bank-accounts`,
    HELP: `/help`,
  },

  CART: {
    MAIN: `/cart`,
  },

  CHECKOUT: {
    MAIN: `/checkout`,
  },

  PAYMENT: {
    RESULT: `/payment/result`,
  },

} as const;